# Generated by Django 5.1.2 on 2024-10-15 21:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('country_code', models.CharField(default='+91', max_length=5, validators=[django.core.validators.RegexValidator(message='Enter a valid country code starting with + followed by 1 to 4 digits.', regex='^\\+\\d{1,4}$')])),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must contain 10 to 15 digits.', regex='^\\d{10,15}$')])),
            ],
        ),
    ]
